runtime: python311

entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT main:app

instance_class: F2
automatic_scaling:
  max_instances: 1
  max_pending_latency: 8s
  min_pending_latency: 4s
  target_throughput_utilization: 0.5
  max_concurrent_requests: 8

inbound_services:
- warmup
