name: Deploy to App Engine

on:
  workflow_dispatch:

jobs:
  deploy_to_app_engine:
    name: Deploy the branch to App Engine
    runs-on: ubuntu-latest

    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: 'write'

    steps:
      # Checkout the latest code from the repo (and submodule[s])
      - uses: 'actions/checkout@v3'
        with:
          repository: EnlitHamster/example-appengine
          submodules: true
          token: ${{ secrets.CI_TOKEN }}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/812641158075/locations/global/workloadIdentityPools/github-actions-pool/providers/wif-provider'
          service_account: 'github-actions-service-account@giga-energy-trade.iam.gserviceaccount.com'

      - id: 'deploy'
        name: 'Deploy platform to Google Cloud - App Engine with no traffic'
        uses: 'google-github-actions/deploy-appengine@v1.2.1'
        with:
          working_directory: ../energy-trade/
          deliverables: app.yaml
          promote: false
          version: production
