name: Deploy to App Engine

on:
  workflow_dispatch:

jobs:
  deploy_to_app_engine:
    name: Deploy the branch to App Engine
    runs-on: ubuntu-latest

    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: 'write'

    steps:
      # Checkout the latest code from the repo (and submodule[s])
      - uses: 'actions/checkout@v3'
        with:
          repository: EnlitHamster/example-appengine
          submodules: true
          token: ${{ secrets.CI_TOKEN }}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/622176417487/locations/global/workloadIdentityPools/gh-pool-16535921079945682774/providers/gh-prov-16535921079945682774'
          service_account: 'github-actions-service-account@playground-tofu-project.iam.gserviceaccount.com'

      - id: 'deploy'
        name: 'Deploy platform to Google Cloud - App Engine'
        uses: 'google-github-actions/deploy-appengine@v1.2.1'
        with:
          working_directory: ../example-appengine/
          deliverables: app.yaml
          version: production
          env_vars: |-
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASS=${{ secrets.DB_PASS }}
            INSTANCE_CONNECTION_NAME=${{ secrets.INSTANCE_CONNECTION_NAME }}
